### ISSUE TITLE
Fix timestamp scalar parsing

### ISSUE THREAD

**Issue by codingconcepts** [codingconcepts/drk#1]
drk tries to parse the following as a time.Time when initially, it should be trying to parse a string:

```yaml
- type: timestamp
  min: 2014-01-01T00:00:00Z
  max: 2024-01-01T23:59:59Z
```

The workaround is to surround the values with quotes but this isn't obvious:

```yaml
- type: timestamp
  min: "2014-01-01T00:00:00Z"
  max: "2024-01-01T23:59:59Z"
```
